language: perl6
perl6:
  - latest
  - '2017.08'
  - '2017.07'
install:
  - rakudobrew build-zef
  - zef install --debug DBIish
  - zef install --debug Bailador
  - zef install --debug Crypt::Bcrypt

matrix:
  allow_failures:
  - perl6: latest
